### ISSUE TITLE
Making requests Before DB is open

### ISSUE THREAD

**Issue by Marc-Morcos** [kovaradam/indexeddb-hooked#1]
Hey, I'm not sure if I'm doing something wrong but im following the documentation
![image](https://user-images.githubusercontent.com/30278842/119168463-eea53b00-ba2e-11eb-911d-a8a7c8f99bc4.png)

App is my main app, but, I am able to make multiple requests before the DB is actually open, leading to trouble.

**Comment by kovaradam** [comment]
Hi, could you please provide me with more details? E.g. where in your component tree are you making those requests or possibly how to replicate this behaviour? Thanks!

**Comment by MarcM0** [comment]
My index simply calls the app, 
![image](https://user-images.githubusercontent.com/30278842/119183608-50bb6b80-ba42-11eb-953b-2455dc1bef8d.png)
in my app file, I directly call open and then, in my app,
![image](https://user-images.githubusercontent.com/30278842/119183687-721c5780-ba42-11eb-9915-b818795e2f94.png)
in which I almost immediately call useRead
![image](https://user-images.githubusercontent.com/30278842/119183882-adb72180-ba42-11eb-9729-8a9fcaf9f19b.png)

**Comment by kovaradam** [comment]
Oh, okay, it is supposed to return `null` value until the database is open, because the `useRead` has to return something. If you want to check if the db is open and then for example render particular components, you can use the promise which is returned from the `open` function and resolves when the db is open.

**Comment by MarcM0** [comment]
alright, thank you
